# Puerto del servidor
server.port=8080

# Oracle Database connection (Universidad)
spring.datasource.url=jdbc:oracle:thin:@192.168.254.215:1521:orcl
spring.datasource.username=practicas
spring.datasource.password=practicas
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hikari Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# No usar scripts automáticos
spring.sql.init.mode=never

# Configuración personalizada usada por ConexionBD.java (si la usas)
app.oracle.url=jdbc:oracle:thin:@192.168.254.215:1521:orcl
app.oracle.user=practicas
app.oracle.password=practicas